### PR TITLE
feat: added login and signup pages

### PR DESCRIPTION
**Pull request by KanekarSnehal**
Created Signup and Login Pages. Please review.

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
good to merge

**Review by dev-enforced — APPROVED** [review]
The code looks good to me!! Well utilised utility classes while developing the webpage:
https://deploy-preview-5--magnet-store.netlify.app/pages/login.html
https://deploy-preview-5--magnet-store.netlify.app/pages/sign-up.html
Good work @KanekarSnehal 

Had a minor query 
image
You can keep the forgot password on left side too as it looks better with the other sections!!

**Comment by KanekarSnehal** [comment]
> The code looks good to me!! Well utilised utility classes while developing the webpage: https://deploy-preview-5--magnet-store.netlify.app/pages/login.html https://deploy-preview-5--magnet-store.netlify.app/pages/sign-up.html Good work @KanekarSnehal
> 
> Had a minor query image You can keep the forgot password on left side too as it looks better with the other sections!!

Hey, thanks for your feedback, I have made the changes.

**Comment by KanekarSnehal** [comment]
Got 2 reviews, merging this PR.

**Pull request merged**
